[package]
name = "cebula-camp"
version = "0.1.0"
authors = ["Stan Drozd <drozdziak1@gmail.com>"]
edition = "2018"

[dependencies]
rpassword = "3.0"
sha3 = "0.8"

[dev-dependencies]
criterion = "0.2"
cebula-camp = {path = "."}

[[bench]]
name = "bytes2string"
harness = false
